
now=$(date +%s)

### Download hosts
wget http://someonewhocares.org/hosts/zero/hosts -O hosts.10-someonewhocares


echo "#### uAdBlock autogenerated hosts ####" > hosts
echo "#### Generated on $(date -d @$now) ####" >> hosts

cat hosts.* >> hosts

echo $now > updated
