
now=$(date +"%m_%d_%Y")

### Download hosts
wget http://someonewhocares.org/hosts/zero/hosts -O hosts.10-someonewhocares


echo "#### uAdBlock autogenerated hosts ####" > hosts
echo "#### Generated on $now ####" >> hosts

cat hosts.* >> hosts

echo $now > updated
