
now=$(date +%s)

### Download hosts
wget https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -O hosts.10-stevenblack


echo "#### uAdBlock autogenerated hosts ####" > hosts
echo "#### Generated on $(date -d @$now) ####" >> hosts

cat hosts.* >> hosts

echo $now > updated
